### ISSUE TITLE
Incompatibility with Windows 

### ISSUE THREAD

**Issue by rokaijano** [kacheryhub/kachery-client#5]
The following import is incompatible with Windows: 

https://github.com/kacheryhub/kachery-client/blob/fdd0783afdde35166a6269cea48604eec79819a0/kachery_client/_feeds.py#L4

Not much testing was made, but it seems that by commenting out the line, the import is successful.

**Comment by magland** [comment]
Please use the following repo instead (although still may not be compatible with windows):
https://github.com/flatironinstitute/kachery-cloud

**Comment by rokaijano** [comment]
Ok, will give it a try! Thanks!
